# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

gems: [jekyll-paginate]

# Setup
title:               Monologue For Dialogue
tagline:             'Mijeong'
description:         'iOS ê°œë°œì ë¯¸ì •ì…ë‹ˆë‹¤. ê°œë°œì— ê´€ë ¨ëœ ì´ëŸ°ì €ëŸ° ë…ë°±ì„ ë‚¨ê¸°ëŠ” ê³³ì…ë‹ˆë‹¤. ê´€ë¦¬ìê°€ ê²Œì„ëŸ¬ì„œ ë‚´ìš©ì´ ë¶€ì‹¤í•  ìˆ˜ ìˆìŠµë‹ˆë‹¤. ğŸ  <br> ninevincentg@gmail.com'
url:                 https://mijeongjeon.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:           ë¯¸ì •(Mijeong Jeon)
  url:               https://www.facebook.com/Ninevincent
  email:           ninevincentg@gmail.com

github:
  repo:              https://github.com/MijeongJeon
# Custom vars
# version:             1.0.0
